apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  labels:
    app: symfony
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony-app
        image: pierresylvain/symfony-app:latest
        ports:
        - containerPort: 45663
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: symfony-service
spec:
  type: NodePort
  ports:
    - port: 45663
      targetPort: 45663
      nodePort: 30001
  selector:
    app: symfony
