name: CI/CD Symfony Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Checkout le dépôt
    - name: Checkout repository
      uses: actions/checkout@v2

    # Étape 2: Configurer PHP et Composer
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist

    # Étape 3: Lancer les tests
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    # Étape 4: Construire l'image Docker
    - name: Build Docker image
      run: docker build -t pierresylvain/symfony-app:${{ github.sha }} .

    # Étape 5: Se connecter à DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 6: Pusher l'image sur DockerHub
    - name: Push Docker image
      run: |
        docker tag pierresylvain/symfony-app:${{ github.sha }} pierresylvain/symfony-app:latest
        docker push pierresylvain/symfony-app:latest

  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment.yml